### ISSUE TITLE
您好，请问是否产生了重复操作？

### ISSUE THREAD

**Issue by Mirr0ch1** [cubesky/MiPushFake#1]
您好，我刚刚看到这里 /common 中的 service.sh 与 build.prop 。
前一阵我在强开VoLTE（同样是向build.prop注入条目）的时候用到了VoEnabler的magisk mod （https://forum.xda-developers.com/apps/magisk/module-v4-volte-enabler-t3649613 ）。其中作者进行了一次更新，描述是 "Switched from using service.sh to system.prop" ，我去查看了它的 /common 下文件源码，service.sh 中仅保留了原始的 module-template，build.prop中加入了需要添加的条目。
我将此模块添加到手机后对应的条目顺利应用了。
因此我抖了一个机灵，发现您这个模块中既使用了 script方法，又使用了一个system.prop ，我不会查看日志和最后注入的结果，所以不知真是结果如何，但参照前一个模块产生的作用和修改，我怀疑产生了重复操作。

**Comment by cubesky** [comment]
因为设置的 key 是相同的，所以只会发生覆盖，不会发生副作用，这是当时有人报告给我一个插入失败的问题时发现，有些设备上只用 system.prop 会导致插入失败

**Comment by Mirr0ch1** [comment]
感谢！学习了。
